# Generated by Django 2.0.3 on 2020-06-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200602_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pastaItems',
            field=models.ManyToManyField(blank=True, related_name='pastaItems', to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pizItems',
            field=models.ManyToManyField(blank=True, related_name='pizItems', to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='platItems',
            field=models.ManyToManyField(blank=True, related_name='platItems', to='orders.Platter'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='saladItems',
            field=models.ManyToManyField(blank=True, related_name='saladItems', to='orders.Salad'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='subItems',
            field=models.ManyToManyField(blank=True, related_name='subItems', to='orders.Sub'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='orders.Toppings'),
        ),
    ]
